[package]
name = "progress_bar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termsize = "0.1.6"
anyhow = "1.0.58"
colored = "2.0.0"